SOURCE_DIRECTORY = ./src
BUILD_DIRECTORY = ./build
CC = gcc
CFLAGS = -Wall -Werror

conways: $(SOURCE_DIRECTORY)/main.o
	$(CC) $(CFLAGS) -o $(BUILD_DIRECTORY)/conways $(SOURCE_DIRECTORY)/main.o

main.o: $(SOURCE_DIRECTORY)/main.c $(SOURCE_DIRECTORY)/conways.c
	$(CC) $(CFLAGS) -c $(BUILD_DIRECTORY)/main.c



clean:
	rm -rf $(BUILD_DIRECTORY)
	mkdir $(BUILD_DIRECTORY)